"use client";
import {useState} from "react";
import type {ReaderSelection,ReaderAnnotation} from "../lib/reader-types";
import {annotationColor,annotationColors} from "../lib/annotation-color";
import {Highlighter,Underline,Trash2,X,Search} from "./PaperyIcons";
import {SelectionGroup} from "./SelectionGroup";
import {useDialogFocus} from "./use-dialog-focus";
import {SelectionLookup} from "./SelectionLookup";
export function AnnotationComposer({selection,initial,onClose,onSave,onDelete}:{selection:ReaderSelection;initial?:ReaderAnnotation;onDelete?:()=>void;onClose:()=>void;onSave:(style:"highlight"|"underline",note:string,color:string)=>void}){const dialog=useDialogFocus(onClose);const [style,setStyle]=useState<"highlight"|"underline">(initial?.style==="underline"?"underline":"highlight");const [note,setNote]=useState(initial?.note||"");const [color,setColor]=useState(annotationColor(initial?.color));const [tab,setTab]=useState(initial?"annotation":"lookup");return <><button className="modalScrim annotationScrim" onClick={onClose}/><div ref={dialog} className="annotationComposer" role="dialog" aria-modal="true" aria-label={initial?"编辑笔记":"选中文字"}><div className="panelHeader"><div><h2>{initial?"编辑笔记":"选中文字"}</h2></div><button aria-label="关闭笔记编辑" onClick={onClose}><X size={19}/></button></div><blockquote>{selection.quote}</blockquote><SelectionGroup className="panelTabs" label="选中文字操作"><button aria-pressed={tab==="annotation"} className={tab==="annotation"?"active":""} onClick={()=>setTab("annotation")}>标注</button><button aria-pressed={tab==="lookup"} className={tab==="lookup"?"active":""} onClick={()=>setTab("lookup")}><Search size={16}/>释义</button></SelectionGroup>{tab==="lookup"?<SelectionLookup quote={selection.quote}/>:<>{initial?.style!=="bookmark"&&<SelectionGroup className="annotationStyles"><button aria-pressed={style==="highlight"} className={style==="highlight"?"active":""} onClick={()=>setStyle("highlight")}><Highlighter size={17}/>高亮</button><button aria-pressed={style==="underline"} className={style==="underline"?"active":""} onClick={()=>setStyle("underline")}><Underline size={17}/>下划线</button></SelectionGroup>}<div className="colorChoices small">{annotationColors.map(item=><button key={item.color} className={color===item.color?"active":""} aria-label={`标注颜色 ${item.label}`} aria-pressed={color===item.color} style={{background:item.color}} onClick={()=>setColor(item.color)}/>)}</div><textarea aria-label="笔记内容" value={note} onChange={e=>setNote(e.target.value)} placeholder="写下与这段文字有关的想法……"/><div className="composerActions">{initial&&onDelete&&<button className="deleteAnnotationAction" onClick={onDelete}><Trash2 size={17}/>删除笔记</button>}<button className="uiButton dark" onClick={()=>onSave(style,note,color)}>保存笔记</button></div></>}</div></>}
