async(page)=>{
 const checks=[],context=await page.context().browser().newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'}),p=await context.newPage();
 const check=(name,ok,detail)=>checks.push({name,ok,detail});
 await p.addInitScript(()=>{const original=indexedDB.open.bind(indexedDB);indexedDB.open=(...args)=>{const request=original(...args);let success;Object.defineProperty(request,'onsuccess',{get:()=>success,set:handler=>{success=handler}});request.addEventListener('success',event=>setTimeout(()=>success?.call(request,event),500));return request}});
 await p.goto('http://127.0.0.1:3100');await p.locator('.librarySkeleton').waitFor();check('loading has named skeleton and busy surface',await p.locator('.librarySkeleton[role=status]').count()===1&&await p.locator('.appShell').getAttribute('aria-busy')==='true');await p.screenshot({path:'output/ui-0.1.28/design-loading.png'});await p.locator('.appShell[data-ready=true]').waitFor();
 await p.getByRole('button',{name:'用户资料与同步'}).click();await p.getByRole('button',{name:'云同步',exact:true}).click();check('unconfigured Google actions are visibly disabled',await p.getByRole('button',{name:'使用 Google 连接',exact:true}).isDisabled()&&await p.getByRole('button',{name:'立即同步',exact:true}).isDisabled());await p.getByRole('button',{name:'关闭用户设置',exact:true}).last().click();
 const create=p.getByRole('button',{name:'新建分类',exact:true});await create.hover();check('category creation hover has a surface',await create.evaluate(e=>getComputedStyle(e).backgroundColor!=='rgba(0, 0, 0, 0)'));await create.click();await p.getByRole('textbox',{name:'分类名称',exact:true}).fill('可编辑分类');await p.getByRole('button',{name:'保存分类',exact:true}).click();await p.locator('.smallModal').waitFor({state:'detached'});
 const row=p.locator('.categoryRow').filter({has:p.getByRole('button',{name:/^可编辑分类/})}),number=row.locator('em'),actions=row.locator('.categoryActions');await p.mouse.move(1400,30);await p.waitForTimeout(160);const defaultX=(await number.boundingBox()).x;check('category actions hidden by default',await actions.evaluate(e=>getComputedStyle(e).opacity==='0'));await row.hover();await p.waitForTimeout(160);check('category count moves left only while hovered',(await number.boundingBox()).x<defaultX-40);check('category edit/delete become visible on hover',await actions.evaluate(e=>getComputedStyle(e).opacity==='1'));await p.screenshot({path:'output/ui-0.1.28/design-category-hover.png'});await p.mouse.move(1400,30);await p.waitForTimeout(160);check('count returns to the right after hover',Math.abs((await number.boundingBox()).x-defaultX)<1);
 await row.locator('.categoryButton').focus();await p.keyboard.press('Tab');check('keyboard focus reveals category controls',await actions.evaluate(e=>getComputedStyle(e).opacity==='1'));
 await p.getByRole('textbox',{name:'搜索书名或作者',exact:true}).focus();const focus=await p.getByRole('textbox',{name:'搜索书名或作者',exact:true}).evaluate(e=>({innerOutline:getComputedStyle(e).outlineStyle,outerBorder:getComputedStyle(e.parentElement).borderWidth}));check('search focus belongs to the outer field',focus.innerOutline==='none'&&focus.outerBorder==='1px',focus);
 await create.click();await p.getByRole('textbox',{name:'分类名称',exact:true}).fill('可编辑分类');await p.getByRole('button',{name:'保存分类',exact:true}).click();await p.locator('.fieldError').waitFor();check('duplicate category has an inline error',true);await p.getByRole('button',{name:'关闭分类编辑',exact:true}).last().click();
 const importButton=p.getByRole('button',{name:'导入书籍',exact:true});const rect=await importButton.boundingBox();await p.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2);await p.mouse.down();const pressed=await importButton.evaluate(e=>getComputedStyle(e).transform);check('press has an immediate scale response',pressed!=='none',pressed);await p.mouse.move(1400,30);await p.mouse.up();
 await p.evaluate(async()=>{const db=await new Promise(r=>{const q=indexedDB.open('papery-library',3);q.onsuccess=()=>r(q.result)}),tx=db.transaction('books','readwrite');tx.objectStore('books').put({id:'invalid-file',title:'损坏文件核查',author:'原创核查',category:'未分类',format:'EPUB',progress:0,updatedAt:100,blob:new Blob(['broken epub'])});await new Promise(r=>tx.oncomplete=r);db.close()});await p.reload();await p.locator('.bookCard').waitFor();await p.getByRole('button',{name:'阅读《损坏文件核查》',exact:true}).click();await p.locator('.readerError').waitFor({timeout:25000});check('reader parse error remains visible and recoverable',await p.getByRole('button',{name:'返回书库',exact:true}).isVisible());await p.screenshot({path:'output/ui-0.1.28/design-reader-error.png'});
 check('reduced motion disables page animation',await p.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running'&&a.effect?.target?.closest?.('.appShell')).length===0));
 await context.close();return {checks,failures:checks.filter(c=>!c.ok)};
}
