"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, @next/next/no-assign-module-variable */

import { memo, useCallback, useDeferredValue, useEffect, useMemo, useRef, useState } from "react";
import {
  AlignJustify, AppWindow, BarChart3, BookMarked, BookOpen, Bookmark, Camera, Check,
  ChevronLeft, ChevronRight, CircleHelp, Clock3, Columns2, Download, FileText, FolderOpen, Highlighter,
  Library, ListTree, Maximize2, Menu, Minus, MoreHorizontal, PanelLeftClose, PanelLeftOpen,
  PenLine, Plus, Search, Settings2, Sparkles, Trash2, Underline, Upload, X,
} from "lucide-react";
import { BackupSyncGuide } from "./components/BackupSyncGuide";
import { SyncPanel } from "./components/SyncPanel";
import { driveConnected, syncGoogleDrive, type DriveConfig } from "./lib/drive-sync";
import { DocumentReader, warmReaderFormat } from "./components/DocumentReader";
import type {
  AppPreferences, ReaderAnnotation, ReaderApi, ReaderLocation, ReaderSearchResult, ReaderSelection, ReaderSettings, TocItem,
} from "./lib/reader-types";
import { defaultAppPreferences, defaultReaderSettings } from "./lib/reader-types";
import { extractBookCover, readEpubMetadata } from "./lib/book-cover";
import { loadPdfJs } from "./lib/pdf-loader";
import {
  createLocalId, deleteCategory, deleteLocalAnnotation, deleteLocalBook, exportLibraryBackup, getDeviceId, importLibraryBackup, loadCategories, loadLocalAnnotations,
  loadLocalBooks, loadLocalSessions, loadSetting, saveAppPreferences, saveBookProgress, saveCategory,
  saveLocalAnnotation, saveLocalBook, saveLocalSession, saveReaderSettings, saveSetting,
} from "./lib/local-library";
import { getCurrentWindow } from '@tauri-apps/api/window';

type View = "书库" | "阅读" | "笔记" | "数据";

// Tauri 窗口控制 - 仅在 Tauri 环境中生效
let _tauriWindow: ReturnType<typeof getCurrentWindow> | null = null;
try {
  if (typeof window !== 'undefined' && ('__TAURI__' in window || '__TAURI_INTERNALS__' in window)) {
    _tauriWindow = getCurrentWindow();
  }
} catch (e) {
  // Not in Tauri environment
}

function tauriMinimize() {
  try { _tauriWindow?.minimize(); } catch (e) { console.warn('Tauri minimize failed:', e); }
}
function tauriToggleMaximize() {
  try { _tauriWindow?.toggleMaximize(); } catch (e) { console.warn('Tauri toggleMaximize failed:', e); }
}
function tauriClose() {
  try { _tauriWindow?.close(); } catch (e) { console.warn('Tauri close failed:', e); }
}
type Book = { id:string;title:string;author:string;progress:number;type:"TXT"|"EPUB"|"PDF";color:string;category:string;last:string;source:string;blob?:Blob;coverDataUrl?:string|null;currentLocation?:string };
type ReadingSession={id:string;book_id:string;started_at:number;duration_seconds:number;words_read:number};

/** Detect mobile platform (Android/iOS) for responsive behavior differences */
const isMobile=typeof window!=="undefined"&&/android|iphone|ipad|ipod/i.test(navigator.userAgent);

const coverColors=["peach","dark","cream","mint","blue"];

function BookCoverImage({book}:{book:Book}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[book.coverDataUrl]);return book.coverDataUrl&&!failed?<img className="bookCoverImage" src={book.coverDataUrl} alt={`${book.title}封面`} onError={()=>setFailed(true)}/>:null}
function Brand(){return <div className="brand"><div className="brandMark"><BookOpen size={18}/></div><span>Papery</span></div>}
function UiButton({children,className="",onClick,disabled=false}:{children:React.ReactNode;className?:string;onClick?:()=>void;disabled?:boolean}){return <button disabled={disabled} className={`uiButton ${className}`} onClick={onClick}>{children}</button>}
function postLibrary(payload:unknown){if(typeof window!=="undefined"&&!window.location.hostname.endsWith("pages.dev"))return Promise.resolve(undefined);return fetch("/api/library",{method:"POST",headers:{"content-type":"application/json","x-papery-device":getDeviceId()},body:JSON.stringify(payload)}).catch(()=>undefined)}
function normalizeReaderSettings(format:Book["type"],value:ReaderSettings){const merged={...defaultReaderSettings,...value};if(isMobile)merged.spread="single";if(format!=="PDF"){if(merged.horizontalMargin>30)merged.horizontalMargin=Math.min(30,Math.round(merged.horizontalMargin/9));if(merged.horizontalMargin<2)merged.horizontalMargin=2;if(merged.verticalMargin>18)merged.verticalMargin=Math.min(18,Math.round(merged.verticalMargin/8))}return merged}
function stableAnnotationLocator(annotation:ReaderAnnotation){if(annotation.style==="bookmark")return annotation.locator;try{const locator=JSON.parse(annotation.locator) as Record<string,unknown>;if(locator.type!=="txt"&&locator.type!=="epub")return annotation.locator;return JSON.stringify({...locator,quote:typeof locator.quote==="string"?locator.quote:annotation.quote,anchor:true,annotationId:annotation.id})}catch{return annotation.locator}}

export default function Home(){
  const [view,setView]=useState<View>("书库");
  const [books,setBooks]=useState<Book[]>([]);
  const [selectedBook,setSelectedBook]=useState<Book|null>(null);
  const [annotations,setAnnotations]=useState<ReaderAnnotation[]>([]);
  const [categories,setCategories]=useState<string[]>(["未分类"]);
  const [sessions,setSessions]=useState<ReadingSession[]>([]);
  const [search,setSearch]=useState("");const [category,setCategory]=useState("全部");
  const [sidebarOpen,setSidebarOpen]=useState(false);const [immersive,setImmersive]=useState(true);const [readingUi,setReadingUi]=useState(true);
  const [importOpen,setImportOpen]=useState(false);const [categoryOpen,setCategoryOpen]=useState(false);const [bookMenu,setBookMenu]=useState<string|null>(null);
  const [deleteBookTarget,setDeleteBookTarget]=useState<Book|null>(null);
  const [deleteNoteTarget,setDeleteNoteTarget]=useState<ReaderAnnotation|null>(null);
  const [deleteCategoryTarget,setDeleteCategoryTarget]=useState<string|null>(null);
  const [readerSettingsOpen,setReaderSettingsOpen]=useState(false);const [appSettingsOpen,setAppSettingsOpen]=useState(false);const [tocOpen,setTocOpen]=useState(false);const [bookSearchOpen,setBookSearchOpen]=useState(false);
  const [profileOpen,setProfileOpen]=useState(false);const [edgeCue,setEdgeCue]=useState<"left"|"right"|null>(null);
  const [readerSettings,setReaderSettings]=useState<ReaderSettings>(defaultReaderSettings);const [appPreferences,setAppPreferences]=useState<AppPreferences>(defaultAppPreferences);
  const [readerApi,setReaderApi]=useState<ReaderApi|null>(null);const [location,setLocation]=useState<ReaderLocation>({locator:"",progress:0,page:1,totalPages:1,chapterTitle:"正文",chapterIndex:0,chapterCount:1});const [toc,setToc]=useState<TocItem[]>([]);
  const [readerInitialLocation,setReaderInitialLocation]=useState<string|undefined>();
  const [selection,setSelection]=useState<ReaderSelection|null>(null);const [editingNote,setEditingNote]=useState<ReaderAnnotation|null>(null);const [toast,setToast]=useState("");
  const [sessionElapsed,setSessionElapsed]=useState(0);
  const [syncOpen,setSyncOpen]=useState(false),[syncLabel,setSyncLabel]=useState("仅保存在本机"),[helpOpen,setHelpOpen]=useState(false);
  const touchStart=useRef({x:0,y:0});const sessionStart=useRef<number|null>(null);const pendingLocator=useRef<string|null>(null);const selectionGuard=useRef(0);const progressTimer=useRef<number|null>(null);const pendingProgress=useRef<{bookId:string;location:ReaderLocation}|null>(null);const booksRef=useRef<Book[]>([]);
  const renderedReaderSettings=useDeferredValue(readerSettings);
  const selectedBookId=selectedBook?.id,selectedBookType=selectedBook?.type;

  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),1800)};

  useEffect(()=>{const ignoreBenignResizeLoop=(event:ErrorEvent)=>{if(/^ResizeObserver loop (?:limit exceeded|completed with undelivered notifications)/.test(event.message)){event.preventDefault();event.stopImmediatePropagation()}};window.addEventListener("error",ignoreBenignResizeLoop,true);return()=>window.removeEventListener("error",ignoreBenignResizeLoop,true)},[]);

  // Mobile back navigation: use History API so Android back gesture returns to previous view
  useEffect(()=>{if(!isMobile)return;const handlePop=()=>{setView(current=>{if(current==="阅读")return"书库";if(current==="笔记"||current==="数据")return"书库";return current})};window.addEventListener("popstate",handlePop);return()=>window.removeEventListener("popstate",handlePop)},[]);
  const pushHistory=useCallback(()=>{if(isMobile)window.history.pushState({view:true},"")},[]);

  useEffect(()=>{(async()=>{
    const settled=await Promise.allSettled([loadLocalBooks(),loadLocalAnnotations(),loadCategories(),loadSetting<AppPreferences>("app"),loadLocalSessions()]);
    const localBooks=settled[0].status==="fulfilled"?settled[0].value:[],localAnnotations=settled[1].status==="fulfilled"?settled[1].value:[],localCategories=settled[2].status==="fulfilled"?settled[2].value:[],prefs=settled[3].status==="fulfilled"?settled[3].value:null,localSessions=settled[4].status==="fulfilled"?settled[4].value:[];
    for(const record of localBooks){const cached=await loadSetting<string>(`cover:${record.id}`).catch(()=>null);if(cached)record.coverDataUrl=cached;}
    const restored:Book[]=localBooks.map((record,index)=>{let progress=record.progress,currentLocation=record.currentLocation;
      // Merge localStorage fallback: localStorage is written synchronously on every
      // page-turn so it is always >= IDB freshness. Prefer it when progress >= IDB.
      try{const ls=localStorage.getItem(`papery-progress-${record.id}`);if(ls){const cached=JSON.parse(ls) as {p:number;l:string;t:number};if(cached.t>=record.updatedAt&&cached.l){progress=cached.p;currentLocation=cached.l}}}catch{}
      return{id:record.id,title:record.title,author:record.author,progress,type:record.format,color:coverColors[index%coverColors.length],category:record.category,last:"本地保存",source:URL.createObjectURL(record.blob),blob:record.blob,coverDataUrl:record.coverDataUrl,currentLocation}});
    const available:Book[]=restored;const nextPreferences={...defaultAppPreferences,...prefs};setBooks(available);setAnnotations(localAnnotations);setSessions(localSessions);setCategories(Array.from(new Set(["未分类",...localCategories,...restored.map(book=>book.category)])));setAppPreferences(nextPreferences);
    // Restore last-read book: try IDB setting first, fall back to localStorage
    let lastReadId=await loadSetting<string>("last-read-book-id").catch(()=>null);
    if(!lastReadId){try{lastReadId=localStorage.getItem("papery-last-book")}catch{}}
    const lastReadBook=available.find(b=>b.id===lastReadId)||available[0];
    setSelectedBook(lastReadBook||null);
    void (async()=>{for(const record of localBooks){if(record.coverDataUrl||record.format==="TXT")continue;const coverDataUrl=await extractBookCover(record.blob,record.format).catch(()=>null);await saveSetting(`cover:${record.id}`,coverDataUrl);setBooks(current=>current.map(book=>book.id===record.id?{...book,coverDataUrl}:book));setSelectedBook(current=>current?.id===record.id?{...current,coverDataUrl}:current)}})();
    if(lastReadBook&&nextPreferences.startPage==="last-read"){setView("阅读");setReaderInitialLocation(lastReadBook.currentLocation||undefined);}
    if(window.location.hostname.endsWith("pages.dev"))fetch("/api/library",{headers:{"x-papery-device":getDeviceId()}}).then(r=>r.ok?r.json():null).then(data=>{if(data?.sessions&&!localSessions.length)setSessions(data.sessions.map((item:ReadingSession,index:number)=>({...item,id:item.id||`remote-${item.started_at}-${index}`})));}).catch(()=>undefined);
  })();},[]);

  useEffect(()=>{if(!selectedBookId||!selectedBookType)return;let active=true;loadSetting<ReaderSettings>(`reader:${selectedBookId}`).then(value=>{if(active)setReaderSettings(normalizeReaderSettings(selectedBookType,{...defaultReaderSettings,...value}))});return()=>{active=false}},[selectedBookId,selectedBookType]);
  useEffect(()=>{if(!selectedBookId)return;const timer=window.setTimeout(()=>{saveReaderSettings(selectedBookId,readerSettings);postLibrary({action:"save-preferences",preferences:{app:appPreferences,categories,readerSettings}})},400);return()=>clearTimeout(timer)},[readerSettings,selectedBookId,appPreferences,categories]);
  useEffect(()=>{saveAppPreferences(appPreferences)},[appPreferences]);
  useEffect(()=>{booksRef.current=books},[books]);
  useEffect(()=>{if(view!=="书库"||!selectedBookType)return;const timer=window.setTimeout(()=>warmReaderFormat(selectedBookType),250);return()=>clearTimeout(timer)},[view,selectedBookType]);

  const flushProgress=useCallback(()=>{const pending=pendingProgress.current;if(!pending)return;pendingProgress.current=null;const rounded=Math.round(pending.location.progress);const book=booksRef.current.find(item=>item.id===pending.bookId);setBooks(current=>current.map(item=>item.id===pending.bookId?{...item,progress:rounded,currentLocation:pending.location.locator,last:"刚刚"}:item));setSelectedBook(current=>current&&current.id===pending.bookId?{...current,progress:rounded,currentLocation:pending.location.locator,last:"刚刚"}:current);
    // CRITICAL: synchronous localStorage write survives window close (IndexedDB
    // async transactions may be aborted when Tauri's WebView is destroyed)
    try{localStorage.setItem(`papery-progress-${pending.bookId}`,JSON.stringify({p:pending.location.progress,l:pending.location.locator,t:Date.now()}));localStorage.setItem("papery-last-book",pending.bookId)}catch{}
    saveBookProgress(pending.bookId,pending.location.progress,pending.location.locator).catch(e=>console.warn("[Papery] IDB save failed:",e));if(book)postLibrary({action:"save-book",book:{id:book.id,title:book.title,author:book.author,format:book.type,category:book.category,progress:pending.location.progress,currentLocation:pending.location.locator}})},[]);
  // Tauri programmatic close: flush progress BEFORE the WebView is destroyed.
  // In Tauri v2, registering onCloseRequested PREVENTS the default close, so we
  // must explicitly call destroy() to actually close the window.
  useEffect(()=>{if(!_tauriWindow)return;let unlisten:(()=>void)|null=null;_tauriWindow.onCloseRequested(()=>{flushProgress();try{_tauriWindow?.destroy()}catch{}}).then(fn=>{unlisten=fn}).catch(()=>{});return()=>{unlisten?.()}},[flushProgress]);
  useEffect(()=>{if(view==="阅读"){sessionStart.current=Date.now();const timer=window.setInterval(()=>setSessionElapsed(Math.floor((Date.now()-(sessionStart.current||Date.now()))/60000)),10000);const autoSave=window.setInterval(()=>flushProgress(),5000);return()=>{clearInterval(timer);clearInterval(autoSave)}}flushProgress();if(!sessionStart.current||!selectedBookId)return;const startedAt=sessionStart.current,endedAt=Date.now(),durationSeconds=Math.max(1,Math.round((endedAt-startedAt)/1000));sessionStart.current=null;const session={id:createLocalId(),book_id:selectedBookId,started_at:startedAt,duration_seconds:durationSeconds,words_read:Math.round(durationSeconds*4.2)};setSessions(current=>[session,...current]);saveLocalSession(session);postLibrary({action:"log-session",session:{bookId:selectedBookId,startedAt,endedAt,durationSeconds,wordsRead:session.words_read}})},[view,selectedBookId,flushProgress]);
  const idbThrottle=useRef(0);
  const handleLocation=useCallback((next:ReaderLocation)=>{setLocation(next);setReaderInitialLocation(next.locator);if(!selectedBookId)return;pendingProgress.current={bookId:selectedBookId,location:next};
    // Immediate synchronous localStorage write on every location change so that
    // even an abrupt window kill loses at most one page-turn of progress.
    try{localStorage.setItem(`papery-progress-${selectedBookId}`,JSON.stringify({p:next.progress,l:next.locator,t:Date.now()}));localStorage.setItem("papery-last-book",selectedBookId)}catch{}
    // Throttled direct IDB write (every 2s) as a second persistence layer
    const now=Date.now();if(now-idbThrottle.current>2000){idbThrottle.current=now;saveBookProgress(selectedBookId,next.progress,next.locator).catch(()=>{})}
    if(progressTimer.current)window.clearTimeout(progressTimer.current);progressTimer.current=window.setTimeout(()=>{progressTimer.current=null;flushProgress()},650)},[selectedBookId,flushProgress]);
  useEffect(()=>()=>{if(progressTimer.current)window.clearTimeout(progressTimer.current);flushProgress()},[selectedBookId,flushProgress]);
  useEffect(()=>{const onVisibility=()=>{if(document.hidden)flushProgress()};const onUnload=()=>flushProgress();const onBlur=()=>flushProgress();document.addEventListener("visibilitychange",onVisibility);window.addEventListener("beforeunload",onUnload);window.addEventListener("blur",onBlur);return()=>{document.removeEventListener("visibilitychange",onVisibility);window.removeEventListener("beforeunload",onUnload);window.removeEventListener("blur",onBlur)}},[flushProgress]);
  const handleToc=useCallback((items:TocItem[])=>setToc(items),[]);const handleSelection=useCallback((value:ReaderSelection)=>{if(value.quote){selectionGuard.current=Date.now()+500;setSelection(value)}},[]);
  const tocGo=useCallback((locator:string)=>{readerApi?.goTo(locator);setTocOpen(false)},[readerApi]);
  const bookSearchGo=useCallback((locator:string)=>{readerApi?.goTo(locator);setBookSearchOpen(false)},[readerApi]);
  const closeToc=useCallback(()=>setTocOpen(false),[]);const closeBookSearch=useCallback(()=>setBookSearchOpen(false),[]);
  useEffect(()=>{if(readerApi&&pendingLocator.current){readerApi.goTo(pendingLocator.current);pendingLocator.current=null}},[readerApi]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if(view!=="阅读"||event.defaultPrevented)return;if((event.target as HTMLElement)?.closest?.("input,textarea,select,[contenteditable=true]")||tocOpen||readerSettingsOpen||bookSearchOpen||selection||editingNote)return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="f"){event.preventDefault();setBookSearchOpen(true);return}if(["ArrowRight","PageDown"," "].includes(event.key)){event.preventDefault();readerApi?.next()}if(["ArrowLeft","PageUp"].includes(event.key)){event.preventDefault();readerApi?.prev()}if(event.key==="Escape")setReadingUi(value=>!value);if(event.key.toLowerCase()==="t")setTocOpen(value=>!value)};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[view,readerApi,tocOpen,readerSettingsOpen,bookSearchOpen,selection,editingNote]);
  useEffect(()=>{if(!bookMenu)return;const dismiss=(event:PointerEvent)=>{if(!(event.target as HTMLElement).closest("[data-book-menu-root]"))setBookMenu(null)},escape=(event:KeyboardEvent)=>{if(event.key==="Escape")setBookMenu(null)};document.addEventListener("pointerdown",dismiss);window.addEventListener("keydown",escape);return()=>{document.removeEventListener("pointerdown",dismiss);window.removeEventListener("keydown",escape)}},[bookMenu]);

  const enterReader=(book:Book,locator?:string)=>{warmReaderFormat(book.type);flushProgress();let startingLocation=locator||book.currentLocation;if(!locator){try{const ls=localStorage.getItem(`papery-progress-${book.id}`);if(ls){const cached=JSON.parse(ls) as {p:number;l:string;t:number};startingLocation=cached.l||undefined}}catch{}}if(view==="阅读"&&selectedBook?.id===book.id){if(startingLocation)readerApi?.goTo(startingLocation);return;}setReaderApi(null);pendingLocator.current=locator||null;setReaderInitialLocation(startingLocation);setLocation({locator:startingLocation||"",progress:book.progress,page:1,totalPages:1,chapterTitle:"正在定位…",chapterIndex:0,chapterCount:1});setSessionElapsed(0);setSelectedBook(book);pushHistory();setView("阅读");setReadingUi(true);setSidebarOpen(false);void saveSetting("last-read-book-id",book.id);try{localStorage.setItem("papery-last-book",book.id)}catch{}};
  const reloadSyncedLibrary=useCallback(async()=>{
    const [records,notes,cats,readingSessions]=await Promise.all([loadLocalBooks(),loadLocalAnnotations(),loadCategories(),loadLocalSessions()]);
    const next:Book[]=records.map((record,index)=>({id:record.id,title:record.title,author:record.author,progress:record.progress,type:record.format,color:coverColors[index%coverColors.length],category:record.category,last:"已同步",source:booksRef.current.find(book=>book.id===record.id)?.source||URL.createObjectURL(record.blob),blob:record.blob,coverDataUrl:record.coverDataUrl,currentLocation:record.currentLocation}));
    setBooks(next);setAnnotations(notes);setCategories(Array.from(new Set(["未分类",...cats])));setSessions(readingSessions);setSelectedBook(current=>next.find(book=>book.id===current?.id)||next[0]||null);setSyncLabel("已同步 · "+new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}));
  },[]);
  useEffect(()=>{if(view!=="书库"||syncOpen)return;const timer=window.setInterval(()=>{void loadSetting<DriveConfig>("sync:drive-config").then(config=>{if(!config?.autoSync||!driveConnected()||document.hidden||!navigator.onLine)return;void syncGoogleDrive(setSyncLabel).then(reloadSyncedLibrary).catch(error=>setSyncLabel(error instanceof Error?error.message:"同步失败，数据保留在本机"));})},60000);return()=>clearInterval(timer)},[view,syncOpen,reloadSyncedLibrary]);
  const exportData=async()=>{const blob=await exportLibraryBackup();const fileName=`papery-backup-${new Date().toISOString().slice(0,10)}.json`;if(_tauriWindow){try{const {save}=await import("@tauri-apps/plugin-dialog");const {writeTextFile}=await import("@tauri-apps/plugin-fs");const path=await save({defaultPath:fileName,filters:[{name:"JSON 备份",extensions:["json"]}]});if(!path)return;await writeTextFile(path,await blob.text());notify(`备份已导出至 ${path}`)}catch(e){notify("导出失败："+(e instanceof Error?e.message:"未知错误"))}}else{const url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=fileName;anchor.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);notify("完整数据备份已导出")}};
  const importData=async(file:File)=>{try{await importLibraryBackup(file);notify("数据已合并恢复，正在重新载入");window.setTimeout(()=>window.location.reload(),700)}catch(error){notify(error instanceof Error?error.message:"备份加载失败")}};
  const searchLower=useMemo(()=>search.toLowerCase(),[search]);
  const filteredBooks=useMemo(()=>books.filter(book=>(category==="全部"||book.category===category)&&`${book.title}${book.author}`.toLowerCase().includes(searchLower)),[books,category,searchLower]);
  const categoryBookCounts=useMemo(()=>{const m:Record<string,number>=Object.create(null);for(const b of books){m[b.category]=(m[b.category]||0)+1}return m},[books]);

  const importFiles=async(files:File[])=>{for(const file of files){const extension=file.name.split(".").pop()?.toUpperCase();if(!extension||!["TXT","EPUB","PDF"].includes(extension)){notify(`${file.name} 格式不支持`);continue}const id=createLocalId();let title=file.name.replace(/\.[^.]+$/,"");let author="未知作者";try{if(extension==="EPUB"){const metadata=await readEpubMetadata(file);title=metadata.title||title;author=metadata.author||author;}else if(extension==="PDF"){const pdfjs=await loadPdfJs();pdfjs.GlobalWorkerOptions.workerSrc="/vendor/pdf.worker.min.mjs";const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;const metadata=await pdf.getMetadata();title=(metadata.info as any)?.Title||title;author=(metadata.info as any)?.Author||author;await saveSetting(`analysis:${id}`,{totalPages:pdf.numPages,analyzedAt:Date.now()});pdf.destroy()}else void saveSetting(`analysis:${id}`,{fileSize:file.size,analyzedAt:Date.now()})}catch{}const coverDataUrl=await extractBookCover(file,extension).catch(()=>null);await saveSetting(`cover:${id}`,coverDataUrl);const book:Book={id,title,author,coverDataUrl,progress:0,type:extension as Book["type"],color:coverColors[books.length%coverColors.length],category:"未分类",last:"刚刚",source:URL.createObjectURL(file),blob:file};setBooks(current=>[book,...current]);await saveLocalBook({id,title,author,format:book.type,category:book.category,progress:0,coverDataUrl,blob:file,updatedAt:Date.now()});const headers={"x-papery-device":getDeviceId()};const form=new FormData();form.append("file",file);if(window.location.hostname.endsWith("pages.dev"))fetch("/api/files",{method:"POST",headers,body:form}).then(r=>r.json()).then(upload=>postLibrary({action:"save-book",book:{id,title,author,format:book.type,category:book.category,fileKey:upload.key}})).catch(()=>undefined)}setImportOpen(false);notify(`已导入 ${files.length} 本书`)};

  const moveBook=async(book:Book,nextCategory:string)=>{const updated={...book,category:nextCategory};setBooks(current=>current.map(item=>item.id===book.id?updated:item));setBookMenu(null);if(book.blob)await saveLocalBook({id:book.id,title:book.title,author:book.author,format:book.type,category:nextCategory,progress:book.progress,currentLocation:book.currentLocation,blob:book.blob,updatedAt:Date.now()});postLibrary({action:"save-book",book:{id:book.id,title:book.title,author:book.author,format:book.type,category:nextCategory,progress:book.progress,currentLocation:book.currentLocation}})};
  const removeBook=async()=>{const target=deleteBookTarget;if(!target)return;const remaining=books.filter(item=>item.id!==target.id);setBooks(remaining);setAnnotations(current=>current.filter(item=>item.bookId!==target.id));if(selectedBook?.id===target.id){setSelectedBook(remaining[0]||null);if(view==="阅读")setView("书库")}setBookMenu(null);setDeleteBookTarget(null);URL.revokeObjectURL(target.source);await deleteLocalBook(target.id);postLibrary({action:"delete-book",id:target.id});notify("书籍及其本地记录已删除")};
  const addCategory=async(name:string)=>{const cleaned=name.trim();if(!cleaned||categories.includes(cleaned))return;setCategories(current=>[...current,cleaned]);await saveCategory(cleaned);setCategoryOpen(false);notify("分类已创建")};
  const removeCategory=async(name:string)=>{if(name==="未分类")return;const updatedBooks=books.filter(book=>book.category===name).map(book=>({...book,category:"未分类"}));setBooks(current=>current.map(item=>item.category===name?{...item,category:"未分类"}:item));setCategories(current=>current.filter(c=>c!==name));if(category===name)setCategory("全部");await deleteCategory(name);for(const book of updatedBooks)if(book.blob)await saveLocalBook({id:book.id,title:book.title,author:book.author,format:book.type,category:"未分类",progress:book.progress,currentLocation:book.currentLocation,blob:book.blob,updatedAt:Date.now()});setDeleteCategoryTarget(null);notify("分类已删除，书籍归入未分类")};
  const toggleBookmark=async()=>{if(!selectedBook)return;if(isCurrentPageBookmarked){const target=readerAnnotations.find(item=>item.style==="bookmark"&&item.locator===location.locator);if(target){setAnnotations(current=>current.filter(item=>item.id!==target.id));await deleteLocalAnnotation(target.id);postLibrary({action:"delete-annotation",id:target.id});notify("书签已移除")}}else{saveAnnotation("bookmark","","#f2a257")}};
  const saveAnnotation=async(style:"highlight"|"underline"|"bookmark",note:string,color:string)=>{if(!selectedBook)return;const source=style==="bookmark"?{quote:location.chapterTitle,locator:location.locator}:selection??(editingNote?{quote:editingNote.quote,locator:editingNote.locator}:null);if(!source)return;const now=Date.now();const annotation:ReaderAnnotation={id:editingNote?.id||createLocalId(),bookId:selectedBook.id,style,quote:source.quote,note,locator:source.locator,color,chapterTitle:editingNote?.chapterTitle||location.chapterTitle,progress:editingNote?.progress??location.progress,createdAt:editingNote?.createdAt||now,updatedAt:now};setAnnotations(current=>[annotation,...current.filter(item=>item.id!==annotation.id)]);await saveLocalAnnotation(annotation);postLibrary({action:"save-annotation",annotation:{id:annotation.id,bookId:annotation.bookId,kind:annotation.style,quote:annotation.quote,content:annotation.note,location:annotation.locator,color:annotation.color}});setSelection(null);setEditingNote(null);notify(style==="bookmark"?"书签已保存":"标注与笔记已保存")};
  const deleteAnnotation=async(id:string)=>{setAnnotations(current=>current.filter(item=>item.id!==id));await deleteLocalAnnotation(id);postLibrary({action:"delete-annotation",id});setDeleteNoteTarget(null);notify("笔记已删除")};
  const openAnnotation=(annotation:ReaderAnnotation)=>{const book=books.find(item=>item.id===annotation.bookId);if(book)enterReader(book,stableAnnotationLocator(annotation))};

  const readerAnnotations=useMemo(()=>annotations.filter(item=>item.bookId===selectedBook?.id),[annotations,selectedBook?.id]);
  const isCurrentPageBookmarked=useMemo(()=>{if(!location.locator)return false;return readerAnnotations.some(item=>item.style==="bookmark"&&item.locator===location.locator)},[readerAnnotations,location.locator]);
  const appTheme=useMemo(()=>appPreferences.appTheme==="system"?(typeof window!=="undefined"&&matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"):appPreferences.appTheme,[appPreferences.appTheme]);

  return <main className={`appShell app-${appTheme} density-${appPreferences.density}`}>
    <header className="titleBar"><div className="mobileBrand"><Brand/></div><div className="dragRegion" data-tauri-drag-region/><div className="windowActions"><button aria-label="最小化" onClick={tauriMinimize}><Minus size={14}/></button><button aria-label="最大化" onClick={tauriToggleMaximize}><Maximize2 size={13}/></button><button className="closeWindow" aria-label="关闭" onClick={tauriClose}><X size={15}/></button></div></header>
    <div className={`workspace ${view==="阅读"&&immersive?"readerMode":""}`}>
      <aside className={`sidebar ${sidebarOpen?"open":""}`}><div className="sidebarTop"><Brand/><button className="mobileClose" onClick={()=>setSidebarOpen(false)}><X size={20}/></button></div>
        <nav className="navList">{[["书库",Library],["阅读",BookOpen],["笔记",PenLine],["数据",BarChart3]].map(([label,Icon])=><button key={String(label)} className={view===label?"active":""} onClick={()=>{if(label==="阅读"){if(selectedBook)enterReader(selectedBook);else setImportOpen(true)}else setView(label as View);setSidebarOpen(false)}}><Icon size={19}/><span>{String(label)}</span>{label==="阅读"&&selectedBook&&<i>{Math.round(selectedBook.progress)}%</i>}</button>)}</nav>
        <div className="sidebarShelf"><p>我的分类</p>{categories.map((name,index)=><div key={name} className="categoryRow"><button className="categoryButton" onClick={()=>{setCategory(name);setView("书库")}}><span><b className={`dot dot-${index%4}`}/>{name}</span><em>{categoryBookCounts[name]||0}</em></button>{name!=="未分类"&&<button className="categoryDelete" aria-label={`删除分类 ${name}`} onClick={e=>{e.stopPropagation();setDeleteCategoryTarget(name)}}><X size={13}/></button>}</div>)}<button className="addCategory" onClick={()=>setCategoryOpen(true)}><span><Plus size={14}/>新建分类</span></button></div>
        <div className="sidebarBottom"><button onClick={()=>setHelpOpen(true)}><CircleHelp size={18}/><span>帮助与快捷键</span></button><button onClick={()=>setAppSettingsOpen(true)}><Settings2 size={18}/><span>偏好设置</span></button><button className="syncState" onClick={()=>{flushProgress();setView("书库");setSyncOpen(true)}}><span className="avatar" style={appPreferences.avatarDataUrl?{backgroundImage:`url(${appPreferences.avatarDataUrl})`}:undefined}>{!appPreferences.avatarDataUrl&&(appPreferences.profileName.trim()[0]||"P")}</span><div><strong>{appPreferences.profileName||"读者"}</strong><small><i/>{syncLabel}</small></div><MoreHorizontal size={18}/></button></div>
      </aside>
      {sidebarOpen&&<button className="scrim" onClick={()=>setSidebarOpen(false)}/>}<section className="mainPanel">
        {view==="书库"&&<LibraryView books={filteredBooks} allBooks={books} selectedBook={selectedBook} profileName={appPreferences.profileName} search={search} setSearch={setSearch} category={category} categories={categories} setCategory={setCategory} onImport={()=>setImportOpen(true)} onRead={enterReader} onMenu={()=>setSidebarOpen(true)} bookMenu={bookMenu} setBookMenu={setBookMenu} onMove={moveBook} onDelete={setDeleteBookTarget}/>}
        {view==="阅读"&&selectedBook&&<div className={`readerPage texture-${renderedReaderSettings.paperTexture} ${isDarkPage(renderedReaderSettings.pageColor)?"readerDark":""}`} style={{background:renderedReaderSettings.pageColor,color:isDarkPage(renderedReaderSettings.pageColor)?"#d6d3cb":undefined}} onTouchStart={e=>{if(e.touches.length===1)touchStart.current={x:e.touches[0].clientX,y:e.touches[0].clientY}}} onTouchEnd={e=>{if(selectedBook.type!=="TXT"||selectionGuard.current>Date.now())return;const dx=e.changedTouches[0].clientX-touchStart.current.x,dy=e.changedTouches[0].clientY-touchStart.current.y;if(renderedReaderSettings.flow==="paginated"&&Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.5){selectionGuard.current=Date.now()+500;if(dx<0)readerApi?.next();else readerApi?.prev()}}}>
          <button className="readingUiToggle" aria-label={readingUi?"隐藏阅读工具栏":"显示阅读工具栏"} title="点击正文中间区域也可切换工具栏" onClick={()=>setReadingUi(value=>!value)}><Menu size={18}/></button><div className={`readerTop ${readingUi?"visible":""}`}><div className="readerTopLeft"><button onClick={()=>{if(isMobile)setSidebarOpen(true);else setImmersive(value=>!value)}} title={immersive?"显示侧边栏":"进入沉浸模式"}>{immersive?<PanelLeftOpen size={19}/>:<PanelLeftClose size={19}/>}</button><button aria-label="返回书库" onClick={()=>setView("书库")}><ChevronLeft size={20}/><span>返回书库</span></button><i/><div><strong>{selectedBook.title}</strong><small>{location.chapterTitle}</small></div></div><div className="readerTools"><button aria-label="书内搜索" onClick={()=>setBookSearchOpen(true)}><Search size={18}/><span>书内搜索</span></button><button aria-label="目录" onClick={()=>setTocOpen(true)}><ListTree size={18}/><span>目录</span></button><button className={`bookmarkBtn ${isCurrentPageBookmarked?"bookmarked":""}`} onClick={toggleBookmark} title={isCurrentPageBookmarked?"点击移除书签":"添加书签"}><Bookmark size={18} fill={isCurrentPageBookmarked?"currentColor":"none"}/><span>{isCurrentPageBookmarked?"已书签":"书签"}</span></button><button aria-label="排版" onClick={()=>setReaderSettingsOpen(true)}><Settings2 size={18}/><span>排版</span></button></div></div>
          <div className="readingStage" onPointerMove={event=>{if(renderedReaderSettings.flow!=="paginated")return;const rect=event.currentTarget.getBoundingClientRect(),ratio=(event.clientX-rect.left)/rect.width;setEdgeCue(ratio<.25?"left":ratio>=.75?"right":null)}} onPointerLeave={()=>setEdgeCue(null)} onClick={event=>{if(selectionGuard.current>Date.now()||window.getSelection()?.toString())return;const target=event.target as HTMLElement;if(target.closest("button,.tocPanel,.settingsPanel,.annotationComposer,.bookSearchPanel"))return;const rect=event.currentTarget.getBoundingClientRect(),ratio=(event.clientX-rect.left)/rect.width;if(renderedReaderSettings.flow==="paginated"){if(ratio<.25)readerApi?.prev();else if(ratio>=.75)readerApi?.next();else setReadingUi(value=>!value)}else if(ratio>.3&&ratio<.7)setReadingUi(value=>!value)}}><DocumentReader key={selectedBook.id} source={selectedBook.source} format={selectedBook.type} bookId={selectedBook.id} settings={renderedReaderSettings} initialLocation={readerInitialLocation} annotations={readerAnnotations} onApi={setReaderApi} onLocation={handleLocation} onToc={handleToc} onSelection={handleSelection} onEdgeCue={setEdgeCue} onToggleUi={()=>setReadingUi(value=>!value)}/></div>

          <div className={`readerBottom ${readingUi?"visible":""}`}><span>{location.chapterTitle} · 章节 {location.chapterIndex+1}/{Math.max(1,location.chapterCount)}</span><div className="readerProgress"><i style={{width:`${location.progress}%`}}/><span className="progressThumb" style={{left:`${location.progress}%`}}/></div><span>{selectedBook.type==="PDF"?"页码":"阅读位置"} {location.page} / {location.totalPages} · {Math.round(location.progress)}%</span><span className="readTime"><Clock3 size={14}/>本次阅读 {sessionElapsed} 分钟</span></div>
        </div>}
        {view==="笔记"&&<NotesView annotations={annotations} books={books} onMenu={()=>setSidebarOpen(true)} onOpen={openAnnotation} onEdit={setEditingNote} onDelete={setDeleteNoteTarget}/>}
        {view==="数据"&&<StatsView books={books} sessions={sessions} onMenu={()=>setSidebarOpen(true)}/>}
      </section>
    </div>
    {syncOpen&&<SyncPanel onClose={()=>setSyncOpen(false)} onUpdated={()=>void reloadSyncedLibrary()}/>}
    {helpOpen&&<><button className="modalScrim" onClick={()=>setHelpOpen(false)}/><aside className="settingsPanel"><div className="panelHeader"><h2>阅读操作</h2><button aria-label="关闭帮助" onClick={()=>setHelpOpen(false)}><X size={20}/></button></div><p>左右方向键、PageUp / PageDown、空格或鼠标滚轮翻页。点击正文左侧四分之一返回，右侧四分之一前进，中间区域显示或隐藏工具栏。</p><p>手机横向滑动翻页；连续阅读模式上下滑动。PDF 支持双指缩放和放大后拖动。</p><p>选中文字后可划线或写笔记；从笔记进入会返回对应文字。右上角菜单按钮始终可以显示工具栏。</p><p>EPUB 和 TXT 的阅读位置按内容计算，排版变化不会把位置当作固定纸书页码；PDF 显示实际页码。</p></aside></>}
    {tocOpen&&<TocPanel toc={toc} location={location} annotations={readerAnnotations} onClose={closeToc} onGo={tocGo}/>}
    {bookSearchOpen&&readerApi&&<BookSearchPanel api={readerApi} onClose={closeBookSearch} onGo={bookSearchGo}/>}
    {readerSettingsOpen&&<ReaderSettingsPanel format={selectedBook?.type||"TXT"} value={readerSettings} onChange={setReaderSettings} onClose={()=>setReaderSettingsOpen(false)}/>}
    {appSettingsOpen&&<AppSettingsPanel value={appPreferences} onChange={setAppPreferences} onExport={exportData} onImport={importData} onProfile={()=>{setAppSettingsOpen(false);setProfileOpen(true)}} onSync={()=>{setAppSettingsOpen(false);setSyncOpen(true)}} onClose={()=>setAppSettingsOpen(false)}/>}
    {profileOpen&&<ProfilePanel value={appPreferences} onChange={setAppPreferences} onClose={()=>setProfileOpen(false)}/>}
    {selection&&<AnnotationComposer selection={selection} onClose={()=>setSelection(null)} onSave={(style,note,color)=>saveAnnotation(style,note,color)}/>}
    {editingNote&&<AnnotationComposer selection={{quote:editingNote.quote,locator:editingNote.locator}} initial={editingNote} onClose={()=>setEditingNote(null)} onSave={(style,note,color)=>saveAnnotation(style,note,color)}/>}
    {categoryOpen&&<TextModal title="新建分类" placeholder="例如：专业资料" onClose={()=>setCategoryOpen(false)} onConfirm={addCategory}/>}
    {deleteBookTarget&&<ConfirmModal title="删除这本书？" detail={`《${deleteBookTarget.title}》的原文件、阅读进度与相关笔记都会一并删除。`} confirm="删除书籍" onClose={()=>setDeleteBookTarget(null)} onConfirm={removeBook}/>}
    {deleteNoteTarget&&<ConfirmModal title="删除这条笔记？" detail={`“${deleteNoteTarget.quote.length>40?deleteNoteTarget.quote.slice(0,40)+"…":deleteNoteTarget.quote}”的标注与笔记将被永久删除。`} confirm="删除笔记" onClose={()=>setDeleteNoteTarget(null)} onConfirm={()=>deleteAnnotation(deleteNoteTarget.id)}/>}
    {deleteCategoryTarget&&<ConfirmModal title={`删除分类"${deleteCategoryTarget}"？`} detail={`该分类下的书籍将归入"未分类"，分类本身会被删除。`} confirm="删除分类" onClose={()=>setDeleteCategoryTarget(null)} onConfirm={()=>removeCategory(deleteCategoryTarget)}/>}
    {importOpen&&<ImportModal onClose={()=>setImportOpen(false)} onFiles={importFiles}/>} {toast&&<div className="toast"><span>✓</span>{toast}</div>}
  </main>
}

function getGreeting(){const h=new Date().getHours();if(h<6)return"夜深了";if(h<12)return"早上好";if(h<14)return"中午好";if(h<18)return"下午好";return"晚上好"}
function isDarkPage(hex:string){const c=hex.replace("#","");if(c.length<6)return false;const r=parseInt(c.slice(0,2),16),g=parseInt(c.slice(2,4),16),b=parseInt(c.slice(4,6),16);return(r*299+g*587+b*114)/1000<100}
const LibraryView=memo(function LibraryView({books,allBooks,selectedBook,profileName,search,setSearch,category,categories,setCategory,onImport,onRead,onMenu,bookMenu,setBookMenu,onMove,onDelete}:{books:Book[];allBooks:Book[];selectedBook:Book|null;profileName:string;search:string;setSearch:(v:string)=>void;category:string;categories:string[];setCategory:(v:string)=>void;onImport:()=>void;onRead:(b:Book)=>void;onMenu:()=>void;bookMenu:string|null;setBookMenu:(v:string|null)=>void;onMove:(b:Book,c:string)=>void;onDelete:(b:Book)=>void}){
  const [today,setToday]=useState("");useEffect(()=>{const fmt=()=>setToday(new Date().toLocaleDateString("zh-CN",{weekday:"long",month:"long",day:"numeric"}));fmt();const timer=window.setInterval(fmt,60000);return()=>clearInterval(timer)},[]);
  return <div className="page libraryPage"><div className="pageHeader"><div className="headerTitle"><button className="menuButton" onClick={onMenu}><Menu size={21}/></button><div><p suppressHydrationWarning>{today}</p><h1>{getGreeting()}，{profileName||"读者"}</h1></div></div><div className="headerActions"><label className="searchBox"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索书名或作者"/><kbd>Ctrl K</kbd></label><UiButton className="primary" onClick={onImport}><Plus size={18}/>导入书籍</UiButton></div></div>
    {selectedBook&&<section className="continueCard"><div className="continueCopy"><span className="eyebrow"><Sparkles size={14}/>继续阅读</span><h2>{selectedBook.title}</h2><p>{selectedBook.author} · {selectedBook.currentLocation?"已记住阅读位置":"等待开始"}</p><div className="progressLine"><span style={{width:`${selectedBook.progress}%`}}/></div><div className="progressMeta"><span>已读 {Math.round(selectedBook.progress)}%</span><span>{selectedBook.type} 文件</span></div><UiButton className="dark" onClick={()=>onRead(selectedBook)}><BookOpen size={17}/>继续阅读</UiButton></div><div className="heroBook"><div className="bookSpine">PAPERY READER</div><div className="bookFace"><BookCoverImage book={selectedBook}/><small>{selectedBook.author}</small><strong>{selectedBook.title}</strong><span>{selectedBook.type} · 本地书库</span><i>阅读，让时间变得具体</i></div></div><div className="orb orb1"/><div className="orb orb2"/></section>}
    <section className="sectionBlock"><div className="sectionHeading"><div><h2>我的书库</h2><p>{allBooks.length} 本书 · 阅读进度自动保存</p></div><div className="segmented">{["全部",...categories].slice(0,5).map(item=><button key={item} onClick={()=>setCategory(item)} className={category===item?"active":""}>{item}</button>)}</div></div>{allBooks.length===0&&<p className="emptyLibraryHint">书库还是空的。导入第一本 EPUB、PDF 或 TXT，开始阅读。</p>}<div className="bookGrid">{books.map(book=><article className="bookCard" data-book-menu-root={bookMenu===book.id?"true":undefined} key={book.id} onClick={()=>onRead(book)}><div className={`cover ${book.color}`}><span className="typePill">{book.type}</span><BookCoverImage book={book}/><div className="coverText"><small>{book.author}</small><strong>{book.title}</strong></div><div className="coverGlow"/></div><div className="bookInfo"><h3>{book.title}</h3><p>{book.author}</p><div className="bookProgress"><span><i style={{width:`${book.progress}%`}}/></span><em>{Math.round(book.progress)}%</em></div><small>{book.last}阅读</small></div><button className="moreBook" aria-label={`管理《${book.title}》`} onClick={e=>{e.stopPropagation();setBookMenu(bookMenu===book.id?null:book.id)}}><MoreHorizontal size={18}/></button>{bookMenu===book.id&&<div className="bookMenu" onClick={e=>e.stopPropagation()}><small>移动到分类</small>{categories.map(item=><button key={item} className={book.category===item?"active":""} onClick={()=>onMove(book,item)}>{book.category===item&&<Check size={13}/>}<span>{item}</span></button>)}<i className="bookMenuDivider"/><button className="deleteBookAction" onClick={()=>onDelete(book)}><Trash2 size={13}/><span>删除书籍</span></button></div>}</article>)}<button className="addBookCard" onClick={onImport}><span><Plus size={22}/></span><strong>添加一本书</strong><small>支持 TXT · EPUB · PDF</small></button></div></section>
  </div>
});

const TocPanel=memo(function TocPanel({toc,location,annotations,onClose,onGo}:{toc:TocItem[];location:ReaderLocation;annotations:ReaderAnnotation[];onClose:()=>void;onGo:(v:string)=>void}){const [tab,setTab]=useState<"toc"|"marks">("toc");const activeRef=useRef<HTMLButtonElement|null>(null);useEffect(()=>{if(tab==="toc"&&activeRef.current){const timer=window.setTimeout(()=>activeRef.current?.scrollIntoView({block:"center",behavior:"smooth"}),80);return()=>clearTimeout(timer)}},[tab,location.chapterIndex]);return <><button className="modalScrim" onClick={onClose}/><aside className="tocPanel"><div className="panelHeader"><div><small>阅读导航</small><h2>目录与标记</h2></div><button onClick={onClose}><X size={20}/></button></div><div className="panelTabs"><button className={tab==="toc"?"active":""} onClick={()=>setTab("toc")}>目录</button><button className={tab==="marks"?"active":""} onClick={()=>setTab("marks")}>标记 {annotations.length}</button></div><div className="tocList">{tab==="toc"?toc.map((item,index)=><button key={item.id} ref={index===location.chapterIndex?activeRef:undefined} className={index===location.chapterIndex?"active":""} style={{paddingLeft:16+item.level*15}} onClick={()=>onGo(item.locator)}><span>{item.label}</span>{item.page&&<em>第 {item.page} 页</em>}</button>):annotations.map(item=><button key={item.id} onClick={()=>onGo(item.locator)}><span>{item.style==="bookmark"?item.chapterTitle:item.quote}</span><i>{Math.round(item.progress)}%</i></button>)}</div></aside></>});

const BookSearchPanel=memo(function BookSearchPanel({api,onClose,onGo}:{api:ReaderApi;onClose:()=>void;onGo:(locator:string)=>void}){
  const [query,setQuery]=useState("");const [results,setResults]=useState<ReaderSearchResult[]>([]);const [loading,setLoading]=useState(false);
  useEffect(()=>{const value=query.trim();if(!value)return;let cancelled=false;const timer=window.setTimeout(()=>api.search(value).then(items=>{if(!cancelled)setResults(items)}).finally(()=>{if(!cancelled)setLoading(false)}),260);return()=>{cancelled=true;clearTimeout(timer)}},[query,api]);
  return <><button className="modalScrim" onClick={onClose}/><aside className="bookSearchPanel"><div className="panelHeader"><div><small>当前书籍</small><h2>全文搜索</h2></div><button onClick={onClose}><X size={20}/></button></div><label className="bookSearchInput"><Search size={18}/><input autoFocus value={query} onChange={event=>{const value=event.target.value;setQuery(value);setResults([]);setLoading(Boolean(value.trim()))}} placeholder="输入关键词，Enter 搜索"/><kbd>Ctrl F</kbd></label><div className="bookSearchMeta">{loading?"正在检索整本书…":query?`找到 ${results.length}${results.length===100?"+":""} 处结果`:"输入关键词开始搜索"}</div><div className="bookSearchResults">{results.map(item=><button key={item.id} onClick={()=>onGo(item.locator)}><strong>{item.label}</strong><span>{item.excerpt}</span></button>)}{query&&!loading&&!results.length&&<div className="bookSearchEmpty">没有找到相关内容</div>}</div></aside></>;
});

function ReaderSettingsPanel({format,value,onChange,onClose}:{format:Book["type"];value:ReaderSettings;onChange:(v:ReaderSettings)=>void;onClose:()=>void}){
  const set=<K extends keyof ReaderSettings>(key:K,next:ReaderSettings[K])=>onChange({...value,[key]:next});
  const textLayout=format!=="PDF";
  const verticalValue=value.verticalMargin>18?Math.min(18,Math.round(value.verticalMargin/8)):value.verticalMargin,horizontalValue=value.horizontalMargin>30?Math.min(30,Math.round(value.horizontalMargin/9)):value.horizontalMargin;
  return <><button className="modalScrim" onClick={onClose}/><aside className="settingsPanel readerSettingsPanel">
    <div className="panelHeader"><div><small>{format==="PDF"?"PDF 页面":"当前书籍"}</small><h2>{format==="PDF"?"页面显示":"排版与阅读"}</h2></div><button onClick={onClose}><X size={20}/></button></div>
    {textLayout&&<><section><label>字体</label><div className="fontChoices">{[["lxgw","霞鹜文楷"],["serif","宋体衬线"],["sans","清晰黑体"],["system","跟随系统"]].map(([id,name])=><button key={id} className={value.fontFamily===id?"active":""} onClick={()=>set("fontFamily",id as ReaderSettings["fontFamily"])}>{name}</button>)}</div></section>
    <RangeSetting label="字号" value={value.fontSize} min={14} max={32} unit="px" onChange={v=>set("fontSize",v)}/>
    <RangeSetting label="行间距" value={value.lineHeight} min={1.3} max={2.6} step={.1} onChange={v=>set("lineHeight",v)}/>
    <RangeSetting label="段间距" value={value.paragraphSpacing} min={0} max={36} unit="px" onChange={v=>set("paragraphSpacing",v)}/>
    <RangeSetting label="上下边距" value={verticalValue} min={0} max={18} unit="%" onChange={v=>set("verticalMargin",v)}/>
    <RangeSetting label="左右边距" value={horizontalValue} min={2} max={30} unit="%" onChange={v=>set("horizontalMargin",v)}/>
    <section><label>页面颜色</label><div className="colorChoices">{["#eee8dc","#f7f7f4","#dfe8df","#e7e2ef","#141414"].map(color=><button key={color} className={value.pageColor===color?"active":""} style={{background:color}} onClick={()=>set("pageColor",color)}/>)}<label className="customColor" style={{background:value.pageColor}}><input type="color" value={value.pageColor} onChange={event=>set("pageColor",event.target.value)}/><Plus size={15}/></label></div></section>
    <section><label>纸张质感</label><div className="choiceGrid">{[["plain","纯净"],["paper","纸纹"],["soft","柔光"]].map(([id,name])=><button key={id} className={value.paperTexture===id?"active":""} onClick={()=>set("paperTexture",id as ReaderSettings["paperTexture"])}>{name}</button>)}</div></section></>}
    {textLayout?<><section><label>翻页方式</label><div className="choiceRows"><button className={value.flow==="paginated"?"active":""} onClick={()=>set("flow","paginated")}><span>横向翻页<small>方向键、滚轮、点击、横向手势</small></span><i/></button><button disabled={value.spread==="double"} className={value.flow==="scrolled"?"active":""} onClick={()=>set("flow","scrolled")}><span>竖向滚动<small>{value.spread==="double"?"双页模式下不可用":"滚轮与纵向手势"}</small></span><i/></button></div></section>
    <section><label>阅读方式</label><div className="choiceGrid"><button className={value.spread==="single"?"active":""} onClick={()=>set("spread","single")}><FileText size={17}/>单页</button><button className={`spreadDoubleBtn ${value.spread==="double"?"active":""}`} onClick={()=>onChange({...value,spread:"double",flow:"paginated"})}><Columns2 size={17}/>双页</button></div></section></>:<p className="settingsHint">PDF 固定使用单页、竖向连续滚动；缩放请使用阅读页中的独立控件。</p>}
    <UiButton className="dark full readerSettingsDone" onClick={onClose}>完成</UiButton>
  </aside></>;
}
function RangeSetting({label,value,min,max,step=1,unit="",onChange}:{label:string;value:number;min:number;max:number;step?:number;unit?:string;onChange:(v:number)=>void}){const percent=(value-min)/(max-min)*100;return <section><div className="settingLabel"><label>{label}</label><strong>{value}{unit}</strong></div><input className="customRange" style={{background:`linear-gradient(90deg,#ee9d50 ${percent}%,#deddd7 ${percent}%)`}} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(+e.target.value)}/></section>}

function AppSettingsPanel({value,onChange,onExport,onImport,onClose,onProfile,onSync}:{onProfile:()=>void;onSync:()=>void;value:AppPreferences;onChange:(v:AppPreferences)=>void;onExport:()=>void;onImport:(file:File)=>void;onClose:()=>void}){
  const input=useRef<HTMLInputElement>(null),set=<K extends keyof AppPreferences>(key:K,next:AppPreferences[K])=>onChange({...value,[key]:next});
  return <><button className="modalScrim" onClick={onClose}/><aside className="settingsPanel"><div className="panelHeader"><div><small>整个应用</small><h2>偏好设置</h2></div><button onClick={onClose}><X size={20}/></button></div><section><label>个人资料</label><button className="uiButton full" onClick={onProfile}>修改昵称与头像</button></section><section><label>应用外观</label><div className="choiceGrid">{[["light","浅色"],["dark","深色"],["system","跟随系统"]].map(([id,name])=><button key={id} className={value.appTheme===id?"active":""} onClick={()=>set("appTheme",id as AppPreferences["appTheme"])}>{name}</button>)}</div></section><section><label>界面密度</label><div className="choiceGrid"><button className={value.density==="comfortable"?"active":""} onClick={()=>set("density","comfortable")}><AppWindow size={17}/>舒适</button><button className={value.density==="compact"?"active":""} onClick={()=>set("density","compact")}><AlignJustify size={17}/>紧凑</button></div></section><section><label>启动页面</label><div className="choiceRows"><button className={value.startPage==="library"?"active":""} onClick={()=>set("startPage","library")}><span>打开书库<small>从完整书库开始</small></span><i/></button><button className={value.startPage==="last-read"?"active":""} onClick={()=>set("startPage","last-read")}><span>继续上次阅读<small>直接回到最后一本书</small></span><i/></button></div></section><section><label>数据备份</label><input ref={input} hidden type="file" accept="application/json,.json" onChange={event=>{const file=event.target.files?.[0];if(file)onImport(file);event.currentTarget.value=""}}/><div className="choiceGrid"><button onClick={onExport}><Download size={17}/>导出全部数据</button><button onClick={()=>input.current?.click()}><Upload size={17}/>加载备份</button></div></section><p className="settingsHint">备份包含书籍原文件、分类、进度、排版、标注、笔记和阅读记录。加载备份采用合并方式，不会先清空现有数据。</p><BackupSyncGuide onConnect={onSync}/><UiButton className="dark full" onClick={onClose}>完成</UiButton></aside></>;
}

function ProfilePanel({value,onChange,onClose}:{value:AppPreferences;onChange:(v:AppPreferences)=>void;onClose:()=>void}){
  const input=useRef<HTMLInputElement>(null);const [name,setName]=useState(value.profileName);const [avatar,setAvatar]=useState(value.avatarDataUrl);
  const chooseAvatar=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>{const image=new Image();image.onload=()=>{const canvas=document.createElement("canvas"),size=256;canvas.width=size;canvas.height=size;const context=canvas.getContext("2d");if(!context)return;const side=Math.min(image.naturalWidth,image.naturalHeight),sx=(image.naturalWidth-side)/2,sy=(image.naturalHeight-side)/2;context.drawImage(image,sx,sy,side,side,0,0,size,size);setAvatar(canvas.toDataURL("image/jpeg",.86))};image.src=String(reader.result)};reader.readAsDataURL(file)};
  const save=()=>{onChange({...value,profileName:name.trim()||"读者",avatarDataUrl:avatar});onClose()};
  return <><button className="modalScrim" onClick={onClose}/><div className="profilePanel"><div className="panelHeader"><div><small>本地身份</small><h2>个人头像</h2></div><button onClick={onClose}><X size={20}/></button></div><input ref={input} hidden type="file" accept="image/*" onChange={event=>{chooseAvatar(event.target.files?.[0]);event.currentTarget.value=""}}/><button className="profileAvatarPicker" onClick={()=>input.current?.click()} style={avatar?{backgroundImage:`url(${avatar})`}:undefined}><span>{!avatar&&(name.trim()[0]||"P")}</span><i><Camera size={16}/></i></button><p>头像会自动裁剪为正方形，并随应用数据备份。</p><label className="profileNameField"><span>显示名称</span><input value={name} maxLength={20} onChange={event=>setName(event.target.value)} placeholder="输入你的名称"/></label>{avatar&&<button className="removeAvatar" onClick={()=>setAvatar("")}>移除当前头像</button>}<UiButton className="dark full" onClick={save}>保存个人资料</UiButton></div></>;
}

function AnnotationComposer({selection,initial,onClose,onSave}:{selection:ReaderSelection;initial?:ReaderAnnotation;onClose:()=>void;onSave:(style:"highlight"|"underline",note:string,color:string)=>void}){const [style,setStyle]=useState<"highlight"|"underline">(initial?.style==="underline"?"underline":"highlight");const [note,setNote]=useState(initial?.note||"");const [color,setColor]=useState(initial?.color||"#f3b56f");return <><button className="modalScrim annotationScrim" onClick={onClose}/><div className="annotationComposer"><div className="panelHeader"><div><small>选中文字</small><h2>{initial?"编辑笔记":"添加标注"}</h2></div><button onClick={onClose}><X size={19}/></button></div><blockquote>{selection.quote}</blockquote><div className="annotationStyles"><button className={style==="highlight"?"active":""} onClick={()=>setStyle("highlight")}><Highlighter size={17}/>高亮</button><button className={style==="underline"?"active":""} onClick={()=>setStyle("underline")}><Underline size={17}/>下划线</button></div><div className="colorChoices small">{["#f3b56f","#f0d36f","#9ed0b3","#aebee8","#d7a8d8"].map(item=><button key={item} className={color===item?"active":""} style={{background:item}} onClick={()=>setColor(item)}/>)}</div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="写下与这段文字有关的想法……"/><UiButton className="dark full" onClick={()=>onSave(style,note,color)}>保存标注与笔记</UiButton></div></>}

const NotesView=memo(function NotesView({annotations,books,onMenu,onOpen,onEdit,onDelete}:{annotations:ReaderAnnotation[];books:Book[];onMenu:()=>void;onOpen:(a:ReaderAnnotation)=>void;onEdit:(a:ReaderAnnotation)=>void;onDelete:(a:ReaderAnnotation)=>void}){const [query,setQuery]=useState("");const [bookId,setBookId]=useState("全部");const queryLower=useMemo(()=>query.toLowerCase(),[query]);const filtered=useMemo(()=>annotations.filter(item=>(bookId==="全部"||item.bookId===bookId)&&`${item.quote}${item.note}`.toLowerCase().includes(queryLower)),[annotations,bookId,queryLower]);const annotationCountsByBook=useMemo(()=>{const m:Record<string,number>=Object.create(null);for(const a of annotations){m[a.bookId]=(m[a.bookId]||0)+1}return m},[annotations]);return <div className="page simplePage"><div className="pageHeader"><div className="headerTitle"><button className="menuButton" onClick={onMenu}><Menu size={21}/></button><div><p>阅读沉淀</p><h1>标记与笔记</h1></div></div></div><div className="notesLayout"><aside className="noteBooks"><h3>按书籍查看</h3><button className={bookId==="全部"?"active":""} onClick={()=>setBookId("全部")}><span className="miniCover all"><BookMarked size={15}/></span><div><strong>全部书籍</strong><small>{annotations.length} 条记录</small></div></button>{books.map(book=><button className={bookId===book.id?"active":""} key={book.id} onClick={()=>setBookId(book.id)}><span className={`miniCover ${book.color}`}/><div><strong>{book.title}</strong><small>{annotationCountsByBook[book.id]||0} 条记录</small></div></button>)}</aside><section className="noteList"><div className="noteToolbar"><label className="searchBox"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索笔记内容"/></label><span>{filtered.length} 条</span></div>{filtered.length?filtered.map(note=><article className="noteCard" key={note.id} onClick={()=>onOpen(note)}><div className="noteKind">{note.style==="bookmark"?<Bookmark size={15}/>:note.style==="underline"?<Underline size={15}/>:<Highlighter size={15}/>}</div><p>{note.quote}</p>{note.note&&<div className="noteBody">{note.note}</div>}<footer><span>{books.find(book=>book.id===note.bookId)?.title} · {note.chapterTitle} · {Math.round(note.progress)}%</span><time>{new Date(note.updatedAt).toLocaleDateString("zh-CN")}</time><button onClick={e=>{e.stopPropagation();onEdit(note)}}><PenLine size={15}/></button><button className="danger" onClick={e=>{e.stopPropagation();onDelete(note)}}><Trash2 size={15}/></button></footer></article>):<div className="emptyNotes"><BookMarked size={30}/><strong>还没有笔记</strong><span>阅读时选中文字即可添加高亮、下划线与笔记。</span></div>}</section></div></div>});

const StatsView=memo(function StatsView({books,sessions,onMenu}:{books:Book[];sessions:ReadingSession[];onMenu:()=>void}){const total=sessions.reduce((sum,item)=>sum+item.duration_seconds,0),minutes=Math.round(total/60),words=sessions.reduce((sum,item)=>sum+item.words_read,0),days=new Set(sessions.map(item=>new Date(item.started_at).toDateString())).size;const weekLabels=["一","二","三","四","五","六","日"];const today=new Date();const dayOfWeek=today.getDay();const mondayOffset=dayOfWeek===0?-6:1-dayOfWeek;const chartDays=Array.from({length:7},(_,i)=>{const d=new Date(today);d.setDate(today.getDate()+mondayOffset+i);return d});const todayIndex=chartDays.findIndex(d=>d.toDateString()===today.toDateString());const bars=chartDays.map(date=>sessions.filter(item=>new Date(item.started_at).toDateString()===date.toDateString()).reduce((sum,item)=>sum+item.duration_seconds/60,0));const max=Math.max(1,...bars);return <div className="page simplePage"><div className="pageHeader"><div className="headerTitle"><button className="menuButton" onClick={onMenu}><Menu size={21}/></button><div><p>真实阅读记录</p><h1>阅读数据</h1></div></div></div><div className="statGrid"><article className="statHero"><div><span className="eyebrow"><Sparkles size={14}/>累计阅读</span><h2>{Math.floor(minutes/60)}<small>小时</small> {minutes%60}<small>分钟</small></h2><p>来自每次实际进入阅读页的会话记录。</p></div><div className="ring"><strong>{books.length}</strong><small>本书</small></div></article>{[[String(days),"阅读天数","天"],[String(Math.round(words/1000)),"阅读字数","千字"],[String(books.filter(book=>book.progress>=99).length),"读完书籍","本"]].map(([n,l,u])=><article className="smallStat" key={l}><span>{l}</span><h3>{n}<small>{u}</small></h3><em>实时统计</em></article>)}</div><div className="chartRow"><article className="chartCard"><div className="cardTitle"><div><h3>本周阅读</h3><p>每天实际阅读分钟数</p></div><span>共 {Math.round(bars.reduce((a,b)=>a+b,0))} 分钟</span></div><div className="barChart">{bars.map((value,index)=><div key={index}><span style={{height:`${Math.max(3,value/max*100)}%`}} className={index===todayIndex&&value>0?"hot":""}><i>{Math.round(value)}</i></span><small>{weekLabels[index]}</small></div>)}</div></article><article className="distribution"><div className="cardTitle"><div><h3>格式分布</h3><p>当前书库</p></div></div><div className="donut"><div><strong>{books.length}</strong><small>本书</small></div></div><ul>{(["EPUB","PDF","TXT"] as const).map((format,index)=><li key={format}><i className={`c${index+1}`}/>{format}<span>{books.length?Math.round(books.filter(book=>book.type===format).length/books.length*100):0}%</span></li>)}</ul></article></div></div>});

function TextModal({title,placeholder,onClose,onConfirm}:{title:string;placeholder:string;onClose:()=>void;onConfirm:(v:string)=>void}){const [value,setValue]=useState("");return <><button className="modalScrim" onClick={onClose}/><div className="smallModal"><div className="panelHeader"><h2>{title}</h2><button onClick={onClose}><X size={19}/></button></div><input autoFocus value={value} onChange={e=>setValue(e.target.value)} placeholder={placeholder} onKeyDown={e=>{if(e.key==="Enter")onConfirm(value)}}/><UiButton className="dark full" onClick={()=>onConfirm(value)}>确认</UiButton></div></>}
function ConfirmModal({title,detail,confirm,onClose,onConfirm}:{title:string;detail:string;confirm:string;onClose:()=>void;onConfirm:()=>void}){return <><button className="modalScrim" onClick={onClose}/><div className="confirmModal" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><div className="confirmIcon"><Trash2 size={21}/></div><h2 id="confirm-title">{title}</h2><p>{detail}</p><div><button onClick={onClose}>取消</button><button className="danger" onClick={onConfirm}>{confirm}</button></div></div></>}
function ImportModal({onClose,onFiles}:{onClose:()=>void;onFiles:(f:File[])=>void}){const input=useRef<HTMLInputElement>(null);return <><button className="modalScrim" onClick={onClose}/><div className="importModal"><div className="panelHeader"><div><small>真实解析</small><h2>导入本地书籍</h2></div><button onClick={onClose}><X size={20}/></button></div><input ref={input} hidden multiple type="file" accept=".txt,.epub,.pdf" onChange={e=>e.target.files&&onFiles(Array.from(e.target.files))}/><button className="dropZone" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();onFiles(Array.from(e.dataTransfer.files))}}><div><FolderOpen size={27}/></div><strong>选择文件，或拖放到这里</strong><span>将解析元数据、页数、章节和目录</span></button><div className="fileTypes"><span><FileText size={17}/>TXT</span><span><BookOpen size={17}/>EPUB</span><span><FileText size={17}/>PDF</span></div><p className="privacyTip">原始文件保存至本地数据库；开启同步时同时保存至私人空间。</p></div></>}
